language: c
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -qq gcc-arm-embedded python-yaml cmake dosfstools mtools pkg-config libusb-dev

script:
  - PYTHONPATH=/usr/lib/python2.7/dist-packages "make"

